Repository godwokenrises/godwoken, pull requests merged in 2022-12, with the labels that each got.

#884 fix(psc): submit next block is_first
  crates/block-producer/src/psc.rs
Labels: next release

#865 feat: optimized trace and metrics
  Cargo.lock
  Cargo.toml
  crates/block-producer/Cargo.toml
  crates/block-producer/src/block_sync_client.rs
  crates/block-producer/src/lib.rs
  crates/block-producer/src/psc.rs
  crates/block-producer/src/trace.rs
  crates/chain/Cargo.toml
  crates/chain/src/chain.rs
  crates/challenge/Cargo.toml
  crates/generator/Cargo.toml
  crates/generator/src/error.rs
  crates/generator/src/generator.rs
  crates/generator/src/verification/transaction.rs
  crates/godwoken-bin/Cargo.toml
  crates/godwoken-bin/src/main.rs
  crates/godwoken-bin/src/subcommand/migrate/mod.rs
  crates/mem-pool/Cargo.toml
  crates/mem-pool/src/block_sync_server.rs
  crates/mem-pool/src/fee/queue.rs
  crates/mem-pool/src/pool.rs
  crates/metrics/Cargo.toml
  crates/metrics/src/block_producer.rs
  crates/metrics/src/chain.rs
  crates/metrics/src/custodian.rs
  crates/metrics/src/lib.rs
  crates/metrics/src/rpc.rs
  crates/p2p-network/Cargo.toml
  crates/replay-chain/Cargo.toml
  crates/rpc-client/Cargo.toml
  crates/rpc-server/Cargo.toml
  crates/rpc-server/src/in_queue_request_map.rs
  crates/rpc-server/src/lib.rs
  crates/rpc-server/src/registry.rs
  crates/rpc-server/src/server.rs
  crates/telemetry/Cargo.toml
  crates/telemetry/src/lib.rs
  crates/telemetry/src/metric.rs
  crates/telemetry/src/trace.rs
  crates/telemetry/src/trace/format.rs
  crates/telemetry/src/traits.rs
  crates/tests/Cargo.toml
  crates/tools/Cargo.toml
Labels: next release

#893 test(script_tests): add cases for finality
  crates/tests/src/script_tests/custodian_lock.rs
  crates/tests/src/script_tests/mod.rs
  crates/tests/src/script_tests/stake_lock.rs
  crates/tests/src/script_tests/utils/mod.rs
  crates/tests/src/script_tests/utils/rollup_config.rs
  crates/tests/src/script_tests/withdrawal.rs
  crates/tests/src/script_tests/withdrawal/finality.rs
Labels: next release

#886 docs: add submitting_block_process.md
  docs/submitting_block_process.md
Labels: next release

#900 test: add cases for unlock_to_owner
  crates/block-producer/src/withdrawal.rs
Labels: next release

#909 chore: fix `install/ckb-binary-patcher` in gwos/Makefile
  gwos-evm/Makefile
Labels: bug

#916 Update README.md
  README.md
Labels: documentation
